### ISSUE TITLE
[Core][Item] All Trinkets - "Harmful/Damaging"

### ISSUE THREAD

**Issue by husker3011** [GameFreedomGG/Sindragosa#325]
**Decription:**
Trinkets which have "Harmful/damaging" in proc name can proc on every tick of warlocks corruption/unstable ailments/curse of agony/etc. Yet for mages living bomb dot,fireball dot, pyroblast dot, flamestrike dot; priest's SW:pain or vampiric touch; druid's moonfire and insect swarm none work for proccing sundial or stacking illustration (except initial cast/hit). 
Also it seems (not 100% but decent sample size) that dying curse sees corruption's affliction healing portion as spell so dying curse which doesn't have a tag procs twice as fast for warlocks; tho mages (and all casters) can in fact proc dying curse on dots because it doesn't say "harmful/damaging" instead just "your spells".
**How it works:**
Get a trinket which has harmful/damaging (sundial,forge ember,illustration,,...)
Use any warlock dot, you'll get sundial/forge ember procs and multiple illustration stacks (in the future any trinket with harmful/damaging like Flare of heavens, eye of broodmother in ulduar).
Use any mage/priest/druid dot, you'll get 0 sundial procs and 0 illustration stacks (other than initial hit).
Try it with dying curse (no tag except "your spells") and all classes can proc from dots.
**How it should work:**
If you want to make it retail like, all dots should only fish for procs on cast,never on dots ticks.
You could either make all trinkets work like dying curse (remove harmful/damaging tag and fix for example affliction healing talent counting as a spell); OR make warlocks dots not count as "harmful/damaging spells" to equate it to other class' dots procs.
Warlock is a strong class and this is even further pushing towards class stacking compared to other servers. (which you said you wanted to avoid in ulduar questionare)
With this bug it makes 0 sense to give Flare to any dot class except warlocks.
Dying curse is tagless just says "your spells" so it procs from all dots (including mage/priest), but if it was retail-like it would procc off of no dots at all (just fish on cast).
**Source (you should point out proofs of your report, please give us some source):**
Any old wowhead trinket comment section, ctrl+f dots, You'll see they fish for proc (sundial) or stack up (illu/eye of brood) only on cast, never on tick (like corruption currently giving total of 6 illu stacks per cast).

**Comment by husker3011** [comment]
bump before ulduar ._.

**Comment by UltraNix** [comment]
@husker3011 
But all of these trinkets has special flag to proc off from DOT (and it comes from client files). Please, give me that "any old wowhead trinket comment`

**Comment by UltraNix** [comment]
Just tested.
E.g. Illustration of the Dragon Soul proc off only from initial cast of Dot (used Curse of Agony).
@husker3011 Please, retest it.

**Comment by husker3011** [comment]
> Just tested. E.g. Illustration of the Dragon Soul proc off only from initial cast of Dot (used Curse of Agony). @husker3011 Please, retest it.
Just tested on live, here's 6 stacks of illustration from single CoA and all sundial/dying curse proccing in the middle of a CoA (not on cast) 
https://i.imgur.com/vtUU9aQ.png

**Comment by husker3011** [comment]
@UltraNix forgot to tag (idk if edit pings)

**Comment by Godmatik** [comment]
@UltraNix 

It's proccing because of the healing ticks.

**Comment by Godmatik** [comment]
Please test while having "Siphon Life" talent learned in the affliction tree

**Comment by husker3011** [comment]
> Please test while having "Siphon Life" talent learned in the affliction tree

Nope, the screenshot I sent was as demo without "siphon life".

**Comment by UltraNix** [comment]
@husker3011 Please show me your talents.

**Comment by husker3011** [comment]
> @husker3011 Please show me your talents.

Ok I think I found out why both specs proc from dots.
For affli he's correct - talent "Siphon Life" causes the interraction.
What threw me off is that demo was getting it too so I thought it was hardcoded in the dots but its not, for demo its talent "Fel Synergy"  (idk if there's more reasons but just this talent alone does it). This requires you to have the pet out or else it doesn't work.
I dont have access to PTR so I was doing this all on live and its very slow to go reset at trainer and get soul shards constantly. I'm not sure if there's any more bugs hidden in the talents but for now if you fix "Siphon Life"'s heal portion allowing all dots to proc "harmful" (while being a heal, thats kinda funny) and for demos "Fel Synergy" (while you have your pet out) and retest the casts while having a pet out and those two talents it should ideally be fixed; if not, down the talent rabbithole again. These are the talents tradionally used by the 2 specs https://imgur.com/a/EBu3ZLF

@UltraNix sorry for the lack of info in the original report, I dont have easy access to a warlock or ptr so thanks for taking your time and working on it.

**Comment by UltraNix** [comment]
@husker3011 Thanks for that info!

**Comment by husker3011** [comment]
@UltraNix sorry for bugging, out of curiosity since I see the thread is closed now, is it getting fixed/is it coming soon on live?

**Comment by UltraNix** [comment]
@husker3011 Fix is pushed to repo. I don't know if it is present on server.

**Comment by Godmatik** [comment]
@husker3011 my guess is not until next server restart probably Wednesday when Ulduar is released

**Comment by husker3011** [comment]
@UltraNix seems like demo isnt fixed but affli is; if you wanna take more stabs at it here are the talents (with personal buffs + felguard pet out) https://i.imgur.com/F94gacx.png ❤️

**Comment by UltraNix** [comment]
@husker3011 Should be okay with the next update.
